source 'https://cdn.cocoapods.org/'
# TmkTranslationSDK 的 podspec 发布在此公开 spec 仓库。
source 'https://github.com/timekettle/TmkTranslationSDK-iOS.git'

platform :ios, '15.0'

target 'SDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKDemo
  pod 'TmkTranslationSDK', :podspec => 'https://raw.githubusercontent.com/timekettle/TmkTranslationSDK-iOS/rc/Specs/TmkTranslationSDK/1.3.1-rc.4/TmkTranslationSDK.podspec'
  pod 'SnapKit'

  target 'SDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKDemoUITests' do
    # Pods for testing
  end

end
