name: match
 
on:
  workflow_dispatch:
 
jobs:
  match:
    runs-on: macos-14

    permissions:
      contents: write

    steps:
    # 拉取主仓库代码和子模块
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        submodules: recursive  # 拉取子模块
        fetch-depth: 0    # 完整克隆，避免浅克隆导致子模块无法正确更新

    # 缓存 Git 子模块
    - name: Cache Git submodules
      uses: actions/cache@v4
      with:
        path: |
          .git/modules
        key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
        restore-keys: |
          ${{ runner.os }}-submodules-

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Match release
      env:
        MATCH_GIT_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }} # 后续能否不依赖此密码
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
      run: |
        bundle exec fastlane match development